#!/bin/bash

#echo "Enter number"
#read num
num=$1
len=${#num}
#echo $len
sum=0
num2=$num

while [ $num2 -ne 0 ]
do
  rem=$((num2%10))
  num2=$((num2/10))
  pow=$((rem**len))
  #echo $pow
  sum=$((sum+pow))
done
if [[ $sum -eq $num ]]
then
  chk=1
  echo "$num is an armstrong number"
else
  chk=0
  echo "$num is not an armstrong number"
fi

echo "check=$chk" > armstrong_file.txt
echo "number=$num" >> armstrong_file.txt 
