#!bin/bash
if [[ $1 -eq 1 ]]
then
   echo "$2 is Armstrong"
else
   num=$2
   len=${#num}
   sum=0
   while [ $num -ne 0 ]
   do
     rem=$((num%10))
     num=$((num/10))
     pow=$((rem**len))
     sum=$((sum+pow))
   done
   echo "$2 is not Armstrong : $sum"
fi
 
