#!bin/bash
echo "Enter the number"
read num

num2=$num
rev=0

while [ $num -gt 0 ]
do
   rem=$((num % 10))
   rev=$((rev * 10 + rem))
   num=$((num / 10))
done

if [ $num2 -eq $rev ]
then 
    echo "$num2 is palindrome"
else
    echo "$num2 is not palindrome"
fi   
