#!bin/bash

if [ $# -eq 0 ]
then
  echo "Enter the number"
  read num 
else
  num=$1
fi
num2=$num
rev=0

while [ $num2 -gt 0 ]
do
   rem=$((num2 % 10))
   rev=$((rev * 10 + rem))
   num2=$((num2 / 10))
done

echo "reverse of $num is $rev"
echo "rvrs=$rev" > ./rev_store.txt 
